version: '3'
services: 
  joomla1:
    image: joomla:latest
    links:
     - mysql
    ports:
     - "8080:80"
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=Pa$$w0rd1
     - JOOMLA_DB_NAME=JoomlaDB
    
  joomla2:
    image:  10.10.40.191/joomla2:latest
    links:
     - mysql
    ports:
     - "8081:80"
    environment:
     - JOOMLA_DB_HOST=mysql:3306
     - JOOMLA_DB_PASSWORD=Pa$$w0rd1
     - JOOMLA_DB_NAME=JoomlaDB
 
  mysql:
    image: mysql:5.7
    environment:
     - MYSQL_ROOT_PASSWORD=Pa$$w0rd1
     - MYSQL_USER=JoomlaUser
     - MYSQL_PASSWORD=JoomlaUser
     - MYSQL_DATABASE=JoomlaDB
    volumes:
     - db_volume:/var/lib/mysql

volumes:
  db_volume:

